### ISSUE TITLE
config toggle for auctions.data "extra, new copy"

### ISSUE THREAD

**Issue by NullCase** [RoboMWM/GPAuctions#64]
It looks like you've solved the data integrity problem.

What about making this auction file saving thing a debug option in the config? Save some trouble later on.

**Comment by NullCase** [comment]
Some follow up on #63. Tested today, created like 400 auctions. They closed and no issues at all.

So let's clean up. Turn off the debug stuff so it's not too spamy. 

So my plan is to send $ today, tomorrow - soon as I can test the next release.

Great job Robo.

**Comment by RoboMWM** [comment]
So you want me to keep this debug feature in the plugin? I was just going to remove it but if you want to keep it there for later use I can do that then.

**Comment by RoboMWM** [comment]
For future reference I did the latter since I guessed from the wording that you probably may want to debug that again in the future, just in case.

Also dropped in here to say thanks for your patience and clear and thorough communication; it's very much appreciated and I never feel "burned out" whenever I see or work on any of your feature requests or bug reports.
